name: Tests
on:
  push:
    branches:
      - 'main'
      - 'development'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest mockito pytest-cov codecov
          pip install -r requirements.txt
      - name: Run tests
        run: |
            pytest --cov=./ --cov-report=xml
            codecov
